### ISSUE TITLE
mod crashes when dark-mode v4 is enabled again

### ISSUE THREAD

**Issue by Infernogd** [hiimjustin000/IntegratedDemonlist#5] opened 2024-07-08 20:17 UTC
Yeah mod crashes when dark mode v4 mod is enabled again!  Please fix again thanks :)

**Comment by hiimjasmine00** [comment] 2024-07-08 21:11
Bug caused by DarkMode V4, forwarding this to @iArtie

Caused by this line of code -> https://github.com/v1.0.2/DarkMode-V4/blob/master/src/main.cpp#L540

Fixed by https://github.com/iArtie/DarkMode-V4/pull/4

**Closed as not planned by hiimjasmine00** 2024-07-08 21:11 UTC
